import type { CardProps } from '../../shared/ui/Card';

export const testCards: CardProps[] = [
	{
		avatar: 'https://i.pravatar.cc/150?img=1',
		name: 'Иван',
		city: 'Москва',
		age: 28,
		likes: 35,
		canTeach: [
			{ text: 'Рисование', color: 'creativity' },
			{ text: 'Фотография', color: 'creativity' },
		],
		wantToLearn: [{ text: 'Английский', color: 'languages' }],
		onMoreClick: () => console.log('Иван'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=2',
		name: 'Елена',
		city: 'Санкт-Петербург',
		age: 25,
		likes: 49,
		canTeach: [{ text: 'Английский', color: 'languages' }],
		wantToLearn: [{ text: 'Рисование', color: 'creativity' }],
		onMoreClick: () => console.log('Елена'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=3',
		name: 'Алексей',
		city: 'Калининград',
		age: 32,
		likes: 32,
		canTeach: [{ text: 'Фотография', color: 'creativity' }],
		wantToLearn: [{ text: 'Тайм-менеджмент', color: 'education' }],
		onMoreClick: () => console.log('Алексей'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=4',
		name: 'Мария',
		city: 'Краснодар',
		age: 24,
		likes: 22,
		canTeach: [{ text: 'Фитнес', color: 'health' }],
		wantToLearn: [{ text: 'Кулинария', color: 'home' }],
		onMoreClick: () => console.log('Мария'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=6',
		name: 'Дмитрий',
		city: 'Казань',
		age: 35,
		likes: 42,
		canTeach: [{ text: 'Бизнес', color: 'business' }],
		wantToLearn: [{ text: 'Фотография', color: 'creativity' }],
		onMoreClick: () => console.log('Дмитрий'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=5',
		name: 'Анна',
		city: 'Красноярск',
		age: 27,
		likes: 31,
		canTeach: [{ text: 'Дизайн', color: 'creativity' }],
		wantToLearn: [{ text: 'Финансы', color: 'business' }],
		onMoreClick: () => console.log('Анна'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=7',
		name: 'Сергей',
		city: 'Екатеринбург',
		age: 40,
		likes: 44,
		canTeach: [{ text: 'Рыбалка', color: 'home' }],
		wantToLearn: [{ text: 'Английский', color: 'languages' }],
		onMoreClick: () => console.log('Сергей'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=8',
		name: 'Ольга',
		city: 'Ростов-на-Дону',
		age: 45,
		likes: 11,
		canTeach: [{ text: 'Английский', color: 'languages' }],
		wantToLearn: [{ text: 'Медитация', color: 'health' }],
		onMoreClick: () => console.log('Ольга'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=9',
		name: 'Николай',
		city: 'Томск',
		age: 21,
		likes: 49,
		canTeach: [{ text: 'Программирование', color: 'education' }],
		wantToLearn: [{ text: 'Дизайн', color: 'creativity' }],
		onMoreClick: () => console.log('Николай'),
	},
];
