import type { CardProps } from '../../shared/ui/Card';

export const testCards: CardProps[] = [
	{
		avatar: 'https://i.pravatar.cc/150?img=1',
		name: 'Иван',
		city: 'Москва',
		age: 28,
		canTeach: [{ text: 'Рисование' }, { text: 'Фотография' }],
		wantToLearn: [{ text: 'Английский' }],
		onMoreClick: () => console.log('Иван'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=2',
		name: 'Елена',
		city: 'Санкт-Петербург',
		age: 25,
		canTeach: [{ text: 'Английский' }],
		wantToLearn: [{ text: 'Рисование' }],
		onMoreClick: () => console.log('Елена'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=3',
		name: 'Алексей',
		city: 'Калининград',
		age: 32,
		canTeach: [{ text: 'Фотография' }],
		wantToLearn: [{ text: 'Тайм-менеджмент' }],
		onMoreClick: () => console.log('Алексей'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=4',
		name: 'Мария',
		city: 'Краснодар',
		age: 24,
		canTeach: [{ text: 'Фитнес' }],
		wantToLearn: [{ text: 'Кулинария' }],
		onMoreClick: () => console.log('Мария'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=5',
		name: 'Дмитрий',
		city: 'Казань',
		age: 35,
		canTeach: [{ text: 'Бизнес' }],
		wantToLearn: [{ text: 'Фотография' }],
		onMoreClick: () => console.log('Дмитрий'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=6',
		name: 'Анна',
		city: 'Красноярск',
		age: 27,
		canTeach: [{ text: 'Дизайн' }],
		wantToLearn: [{ text: 'Финансы' }],
		onMoreClick: () => console.log('Анна'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=7',
		name: 'Сергей',
		city: 'Екатеринбург',
		age: 40,
		canTeach: [{ text: 'Рыбалка' }],
		wantToLearn: [{ text: 'Английский' }],
		onMoreClick: () => console.log('Сергей'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=8',
		name: 'Ольга',
		city: 'Ростов-на-Дону',
		age: 45,
		canTeach: [{ text: 'Английский' }],
		wantToLearn: [{ text: 'Медитация' }],
		onMoreClick: () => console.log('Ольга'),
	},
	{
		avatar: 'https://i.pravatar.cc/150?img=9',
		name: 'Николай',
		city: 'Томск',
		age: 21,
		canTeach: [{ text: 'Программирование' }],
		wantToLearn: [{ text: 'Дизайн' }],
		onMoreClick: () => console.log('Николай'),
	},
];
